#ifndef OCCT_WRAP_H
#define OCCT_WRAP_H

#include "occt_wrap_types.h"
#include "occt_wrap_primitives.h"
#include "occt_wrap_booleans.h"
#include "occt_wrap_transforms.h"
#include "occt_wrap_io.h"
#include "occt_wrap_geom2d.h"
#include "occt_wrap_topology.h"
#include "occt_wrap_xde.h"
#include "occt_wrap_visual.h"
#include "occt_wrap_ais_types.h"
#include "occt_wrap_lighting.h"
#include "occt_wrap_selection.h"
#include "occt_wrap_geom3d.h"
#include "occt_wrap_helix.h"
#include "occt_wrap_text.h"
#include "occt_wrap_dimensions.h"
#include "occt_wrap_operations.h"
#include "occt_wrap_features.h"
#include "occt_wrap_shape_fix.h"
#include "occt_wrap_mass_props.h"
#include "occt_wrap_mesh.h"
#include "occt_wrap_hlr_conversion.h"
#include "occt_wrap_image_texture.h"
#include "occt_wrap_animation.h"
#include "occt_wrap_graphic3d.h"
#include "occt_wrap_prs3d.h"
#include "occt_wrap_math_inttools.h"
#include "occt_wrap_xcaf.h"
#include "occt_wrap_extrema.h"
#include "occt_wrap_lprop.h"
#include "occt_wrap_faircurve.h"
#include "occt_wrap_geomplate.h"

#endif
