(in-package :cl-occt)

(defun help ()
  (format t "~&cl-occt — Common Lisp OCCT parametric CAD~2%")
  (format t "~&Primitives:~%")
  (format t "  (make-box dx dy dz)            — rectangular box~%")
  (format t "  (make-cylinder radius height)  — cylinder~%")
  (format t "  (make-sphere radius)           — sphere~%")
  (format t "  (make-cone r1 r2 height)       — cone~%")
  (format t "~&Booleans:~%")
  (format t "  (cut shape &rest shapes)       — subtract shapes~%")
  (format t "  (fuse shape &rest shapes)      — union shapes~%")
  (format t "  (common shape &rest shapes)    — intersect shapes~%")
  (format t "~&Transforms:~%")
  (format t "  (translate shape dx dy dz)     — move shape~%")
  (format t "  (rotate shape ax ay az deg)    — rotate shape~%")
  (format t "~&STEP I/O:~%")
  (format t "  (write-step shape path)        — export to STEP file~%")
  (format t "  (read-step path)               — import from STEP file~%")
  (format t "~&STL I/O:~%")
  (format t "  (write-stl shape path &key deflection) — export to STL file (binary, deflection=0.1)~%")
  (format t "  (read-stl path)                — import from STL file~%")
  (format t "~&Parametric DSL:~%")
  (format t "  (defmodel name (keys) body)    — define parametric model~%")
  (format t "  (param key)                    — read parameter value~%")
  (format t "  (model-ref name)               — reference another model~%")
  (format t "  (set-param! key value)         — set global parameter~%")
  (format t "  (set-params! &rest kv)         — batch set parameters~%")
  (format t "  (with-params (&rest kv) body)  — local parameter scope~%")
  (format t "~&Introspection:~%")
  (format t "  (help)                         — show this help~%")
  (format t "  *params*                       — global parameter plist~%")
  (format t "  *model-registry*               — registered models~%")
  (values))
