(in-package :cl-occt)

(defun make-helix-curve (&key radius pitch height (left-handed nil) (angle 0.0))
  (make-curve (%make-helix-curve (coerce radius 'double-float)
                                  (coerce pitch 'double-float)
                                  (coerce height 'double-float)
                                  (if left-handed 1 0)
                                  (coerce angle 'double-float))))

(defun make-helix-edge (&key radius pitch height (left-handed nil) (angle 0.0) (on-surface (cffi:null-pointer)))
  (let ((surface-ptr (if (typep on-surface 'surface)
                         (%ptr on-surface)
                         (cffi:null-pointer))))
    (make-shape (%make-helix-edge (coerce radius 'double-float)
                                  (coerce pitch 'double-float)
                                  (coerce height 'double-float)
                                  (if left-handed 1 0)
                                  (coerce angle 'double-float)
                                  surface-ptr))))
