(in-package :cl-occt)

(defclass gprops ()
  ((%volume :initarg :volume :reader gprops-volume)
   (%area :initarg :area :reader gprops-area)
   (%center-of-mass :initarg :center-of-mass :reader gprops-center-of-mass)
   (%inertia-matrix :initarg :inertia-matrix :reader gprops-inertia-matrix)
   (%principal-moments :initarg :principal-moments :reader gprops-principal-moments)
   (%principal-axes :initarg :principal-axes :reader gprops-principal-axes)))

(in-package :cl-occt.impl)

(defun %shape-gprops-internal (shape-ptr)
  (cffi:with-foreign-objects ((com-x :double) (com-y :double) (com-z :double)
                              (inertia :double 6)
                              (pm :double 3)
                              (pa :double 9))
    (let ((volume (%shape-volume shape-ptr))
          (area (%shape-area shape-ptr))
          (com-ok (%shape-center-of-mass shape-ptr com-x com-y com-z))
          (inertia-ok (%shape-inertia shape-ptr inertia 6 pm 3 pa 9)))
      (make-instance 'cl-occt:gprops
        :volume volume
        :area area
        :center-of-mass (when (plusp com-ok)
                          (list (cffi:mem-ref com-x :double)
                                (cffi:mem-ref com-y :double)
                                (cffi:mem-ref com-z :double)))
        :inertia-matrix (when (plusp inertia-ok)
                          (list (cffi:mem-aref inertia :double 0)
                                (cffi:mem-aref inertia :double 1)
                                (cffi:mem-aref inertia :double 2)
                                (cffi:mem-aref inertia :double 3)
                                (cffi:mem-aref inertia :double 4)
                                (cffi:mem-aref inertia :double 5)))
        :principal-moments (when (plusp inertia-ok)
                             (list (cffi:mem-aref pm :double 0)
                                   (cffi:mem-aref pm :double 1)
                                   (cffi:mem-aref pm :double 2)))
        :principal-axes (when (plusp inertia-ok)
                          (list (cffi:mem-aref pa :double 0)
                                (cffi:mem-aref pa :double 1)
                                (cffi:mem-aref pa :double 2)
                                (cffi:mem-aref pa :double 3)
                                (cffi:mem-aref pa :double 4)
                                (cffi:mem-aref pa :double 5)
                                (cffi:mem-aref pa :double 6)
                                (cffi:mem-aref pa :double 7)
                                (cffi:mem-aref pa :double 8)))))))

(in-package :cl-occt)

(defun shape-gprops (shape)
  (unless (shape-p shape)
    (return-from shape-gprops nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-gprops nil))
    (%shape-gprops-internal ptr)))

(defun shape-volume (shape)
  (unless (shape-p shape)
    (return-from shape-volume nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-volume nil))
    (let ((v (%shape-volume ptr)))
      (when (minusp v) (return-from shape-volume nil))
      v)))

(defun shape-area (shape)
  (unless (shape-p shape)
    (return-from shape-area nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-area nil))
    (%shape-area ptr)))

(defun shape-center-of-mass (shape)
  (unless (shape-p shape)
    (return-from shape-center-of-mass nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-center-of-mass nil))
    (cffi:with-foreign-objects ((x :double) (y :double) (z :double))
      (let ((ok (%shape-center-of-mass ptr x y z)))
        (when (zerop ok) (return-from shape-center-of-mass nil))
        (values (cffi:mem-ref x :double)
                (cffi:mem-ref y :double)
                (cffi:mem-ref z :double))))))

(defun shape-inertia (shape)
  (shape-gprops shape))
