(in-package :cl-occt)

(defun fix-shape (shape)
  (unless (shape-p shape)
    (return-from fix-shape nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from fix-shape nil))
    (make-shape (%fix-shape ptr))))

(defun fix-wire (wire face &key (tolerance 0.1))
  (unless (shape-p wire)
    (return-from fix-wire nil))
  (let ((wire-ptr (%ptr wire))
        (face-ptr (when (shape-p face) (%ptr face))))
    (when (or (null wire-ptr) (cffi:null-pointer-p wire-ptr))
      (return-from fix-wire nil))
    (make-shape (%fix-wire wire-ptr
                           (or face-ptr (cffi:null-pointer))
                           (coerce tolerance 'double-float)))))

(defun fix-solid (shape)
  (unless (shape-p shape)
    (return-from fix-solid nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from fix-solid nil))
    (make-shape (%fix-solid ptr))))

(defun fix-edge (edge)
  (unless (shape-p edge)
    (return-from fix-edge nil))
  (let ((ptr (%ptr edge)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from fix-edge nil))
    (make-shape (%fix-edge ptr))))

(defun fix-face (face)
  (unless (shape-p face)
    (return-from fix-face nil))
  (let ((ptr (%ptr face)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from fix-face nil))
    (make-shape (%fix-face ptr))))

(defun shape-analysis-free-edges (shape)
  (unless (shape-p shape)
    (return-from shape-analysis-free-edges nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-analysis-free-edges nil))
    (make-shape (%shape-analysis-free-edges ptr))))

(defun shape-analysis-check-intersections (shape)
  (unless (shape-p shape)
    (return-from shape-analysis-check-intersections nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-analysis-check-intersections nil))
    (let ((count (%shape-analysis-check-intersections ptr)))
      (when (minusp count) (return-from shape-analysis-check-intersections nil))
      count)))

(defun shape-analysis-wire-contains-p (wire point)
  (unless (and (shape-p wire) (listp point) (= (length point) 2))
    (return-from shape-analysis-wire-contains-p nil))
  (let ((ptr (%ptr wire)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-analysis-wire-contains-p nil))
    (not (zerop (%shape-analysis-wire-contains ptr
                  (coerce (first point) 'double-float)
                  (coerce (second point) 'double-float))))))

(defun shape-analysis-contents (shape)
  (unless (shape-p shape)
    (return-from shape-analysis-contents nil))
  (let ((ptr (%ptr shape)))
    (when (or (null ptr) (cffi:null-pointer-p ptr))
      (return-from shape-analysis-contents nil))
    (list :solids (count-shape-subshapes shape :solid)
          :shells (count-shape-subshapes shape :shell)
          :faces (count-shape-subshapes shape :face)
          :wires (count-shape-subshapes shape :wire)
          :edges (count-shape-subshapes shape :edge)
          :vertices (count-shape-subshapes shape :vertex))))
