(in-package :cl-occt)

(defclass viewer ()
  ((%driver :initarg :driver :reader %driver)
   (%viewer :initarg :viewer :reader %viewer)
   (%view   :initarg :view   :reader %view)))

(defun viewer-p (v)
  (typep v 'viewer))

(defun make-viewer ()
  (let* ((driver (%create-graphic-driver))
         (v3d-viewer (%v3d-create-viewer driver))
         (view   (%v3d-create-view v3d-viewer))
         (wrapped (make-instance 'viewer
                    :driver driver :viewer v3d-viewer :view view)))
    (tg:finalize wrapped (lambda () (free-viewer wrapped)))
    wrapped))

(defun free-viewer (v)
  (when (viewer-p v)
    (let ((driver (%driver v))
          (v3d-viewer (%viewer v))
          (view (%view v)))
      (when (and view (not (cffi:null-pointer-p view)))
        (%v3d-free-view view))
      (when (and v3d-viewer (not (cffi:null-pointer-p v3d-viewer)))
        (%v3d-free-viewer v3d-viewer))
      (when (and driver (not (cffi:null-pointer-p driver)))
        (%free-graphic-driver driver))
      (setf (slot-value v '%driver) (cffi:null-pointer)
            (slot-value v '%viewer) (cffi:null-pointer)
            (slot-value v '%view) (cffi:null-pointer)))))

(defun fit-all (v)
  (when (viewer-p v)
    (let ((view (%view v)))
      (when (and view (not (cffi:null-pointer-p view)))
        (%v3d-fit-all view)))))

(defun must-be-resized (v)
  (when (viewer-p v)
    (let ((view (%view v)))
      (when (and view (not (cffi:null-pointer-p view)))
        (%v3d-view-must-be-resized view)))))

(defmacro with-viewer ((var) &body body)
  `(let ((,var (make-viewer)))
     (unwind-protect (progn ,@body)
       (free-viewer ,var))))
