(in-package :cl-occt)

(defun make-wedge (dx dy dz &optional ltx xmin zmin xmax zmax)
  (if (and xmin zmin xmax zmax)
      (make-shape (%make-wedge-corner (coerce dx 'double-float)
                                      (coerce dy 'double-float)
                                      (coerce dz 'double-float)
                                      (coerce xmin 'double-float)
                                      (coerce zmin 'double-float)
                                      (coerce xmax 'double-float)
                                      (coerce zmax 'double-float)))
      (make-shape (%make-wedge-full (coerce dx 'double-float)
                                    (coerce dy 'double-float)
                                    (coerce dz 'double-float)
                                    (coerce (or ltx 0) 'double-float)))))
