(defpackage :cl-occt.impl
  (:use :cl :cffi)
  (:export
   :%make-box
   :%make-cylinder
   :%make-sphere
   :%make-cone
   :%make-torus
   :%make-prism
   :%make-revol
   :%boolean-cut
   :%boolean-fuse
   :%boolean-common
   :%boolean-section
   :%translate
   :%rotate
   :%write-step
   :%read-step
   :%write-stl
   :%read-stl
   :%free-shape
   :%free-geom2d
   :%make-pnt2d
   :%make-vec2d
   :%make-dir2d
   :%make-line-2d
   :%make-circle-2d
   :%make-edge-line-2d
   :%make-edge-line-3d
   :%make-edge-circle-2d
   :%make-edge-arc-2d
     :%make-compound
     :%add-to-compound
     :%compound-is-empty
     :%shape-is-compound
     :%make-wire
     :%make-face
   :%make-face-on-plane
    :%get-error-code
    :%get-error-message
    :%xde-new-doc
    :%xde-free-doc
    :%xde-read-step
    :%xde-write-step
    :%xde-get-root-count
    :%xde-get-root-path
    :%xde-get-child-count
    :%xde-get-child-path
    :%xde-get-shape-at
    :%xde-get-name-at
    :%xde-get-color-at
     :%xde-get-location-at
     :%xde-add-part
     :%create-graphic-driver
     :%free-graphic-driver
     :%v3d-create-viewer
     :%v3d-free-viewer
     :%v3d-create-view
     :%v3d-free-view
     :%v3d-fit-all
     :%v3d-view-must-be-resized
     :%create-neutral-window
     :%free-neutral-window
     :%ais-create-context
     :%ais-free-context
     :%ais-create-shape
     :%ais-free-shape
     :%ais-context-display
     :%ais-context-erase
     :%ais-context-remove
     :%ais-context-remove-all
     :%ais-context-is-displayed
      :make-shape
    :make-geom2d
    :*params*
   :model
   :make-model
   :model-name
   :model-fn
   :model-param-keys
   :model-model-deps
   :model-dependents
   :model-dirty
    :model-cached-shape
    :model-last-param-hash
    :model-color
    :model-display-name
    :model-layer
   :register-model
   :find-model
   :unregister-model
   :dirty-model!
   :propagate-changes
   :topological-sort
   :*model-registry*))

(defpackage :cl-occt
  (:use :cl :cl-occt.impl)
  (:shadow :model-color :model-display-name :model-layer)
  (:export
   :shape
   :shape-p
   :geom2d
   :geom2d-p
   :make-pnt2d
   :make-vec2d
   :make-dir2d
   :make-line2d
   :make-circle2d
   :make-edge
   :make-edge-3d
   :make-circle-edge
   :make-circular-arc
   :make-wire
   :make-face
   :make-face-on-plane
   :make-box
   :make-cylinder
   :make-sphere
   :make-cone
   :make-torus
   :make-prism
   :make-revol
   :cut
   :fuse
   :common
   :section
   :translate
   :rotate
   :write-step
   :read-step
   :write-stl
    :read-stl
    :make-compound
    :add-to-compound
    :compound-shape-p
    :read-step-assembly
   :write-step-assembly
   :write-dag-models-to-step
   :read-step-into-dag
   :assembly
   :make-part
   :make-assembly
   :assembly-shape
   :assembly-name
   :assembly-color
   :assembly-location
   :assembly-children
   :assembly-leaf-p
   :assembly-branch-p
   :model-color
   :model-display-name
   :model-layer
   :defmodel
   :param
   :model-ref
   :set-param!
   :set-params!
   :with-params
   :*local-params*
   :help
   :*params*
    :*model-registry*
    :find-model
    :register-model
    :unregister-model
    :viewer
    :viewer-p
    :make-viewer
    :free-viewer
    :fit-all
     :must-be-resized
     :with-viewer
     :ais-context
     :ais-context-p
     :ais-object
     :ais-object-p
     :ais-create-context
     :ais-free-context
     :ais-create-shape
     :ais-free
     :ais-display
     :ais-erase
     :ais-remove
     :ais-remove-all
     :ais-displayed-p))
