(defpackage :cl-occt.impl
  (:use :cl :cffi)
  (:export
   :%make-box
   :%make-cylinder
   :%make-sphere
   :%make-cone
   :%make-torus
   :%make-prism
   :%make-revol
   :%boolean-cut
   :%boolean-fuse
   :%boolean-common
   :%boolean-section
   :%translate
   :%rotate
   :%write-step
   :%read-step
   :%write-stl
   :%read-stl
   :%free-shape
   :%free-geom2d
   :%make-pnt2d
   :%make-vec2d
   :%make-dir2d
   :%make-line-2d
   :%make-circle-2d
   :%make-edge-line-2d
   :%make-edge-line-3d
   :%make-edge-circle-2d
   :%make-edge-arc-2d
     :%make-compound
     :%add-to-compound
     :%compound-is-empty
     :%shape-is-compound
     :%make-wire
     :%make-face
   :%make-face-on-plane
    :%get-error-code
    :%get-error-message
    :%xde-new-doc
    :%xde-free-doc
    :%xde-read-step
    :%xde-write-step
    :%xde-get-root-count
    :%xde-get-root-path
    :%xde-get-child-count
    :%xde-get-child-path
    :%xde-get-shape-at
    :%xde-get-name-at
    :%xde-get-color-at
     :%xde-get-location-at
     :%xde-add-part
     :%create-graphic-driver
     :%free-graphic-driver
     :%v3d-create-viewer
     :%v3d-free-viewer
     :%v3d-create-view
     :%v3d-free-view
     :%v3d-fit-all
     :%v3d-view-must-be-resized
     :%create-neutral-window
     :%free-neutral-window
     :%ais-create-context
     :%ais-free-context
     :%ais-create-shape
     :%ais-free-shape
     :%ais-context-display
     :%ais-context-erase
     :%ais-context-remove
     :%ais-context-remove-all
      :%ais-context-is-displayed
      :%v3d-view-set-bg-color
      :%ais-context-set-color
      :%ais-context-unset-color
      :%ais-context-set-display-mode
       :%v3d-view-set-proj
        :%v3d-view-set-eye
        :%v3d-view-get-eye-x
        :%v3d-view-get-eye-y
        :%v3d-view-get-eye-z
        :%v3d-view-set-target
        :%v3d-view-get-target-x
        :%v3d-view-get-target-y
        :%v3d-view-get-target-z
        :%v3d-view-set-up
        :%v3d-view-get-up-x
        :%v3d-view-get-up-y
        :%v3d-view-get-up-z
        :%v3d-view-set-projection-type
        :%v3d-view-get-projection-type
        :%v3d-view-set-fov
        :%v3d-view-get-fov
       :%v3d-view-set-clip-planes
       :%v3d-view-fit-all-shape
       :%v3d-view-pan
       :%v3d-view-zoom
       :%v3d-view-rotate
       :%v3d-view-reset
       :%v3d-view-set-msaa
       :%v3d-view-get-msaa
       :%make-light-ambient
       :%make-light-directional
       :%make-light-positional
       :%make-light-spot
       :%light-free
       :%light-set-angle
       :%light-set-concentration
       :%light-set-position
       :%v3d-viewer-add-light
       :%v3d-viewer-remove-light
       :%v3d-viewer-light-on
       :%v3d-viewer-light-off
       :%light-is-on
       :%light-set-color
       :%light-set-intensity
       :%light-set-direction
       :%light-set-headlight
       :%light-set-shadows
       :%v3d-viewer-default-lights
       :%v3d-viewer-grid-active
       :%v3d-view-set-bg-gradient
       :%v3d-view-reset-background
       :%v3d-view-set-computed-mode
       :%v3d-view-computed-mode
       :%v3d-view-set-back-face-model
       :%v3d-view-set-frustum-culling
       :%v3d-view-redraw
       :%v3d-view-set-immediate-update
       :%ais-text-label-set-angle
       :%ais-text-label-set-hjustification
       :%ais-text-label-set-vjustification
       :%ais-text-label-set-color-sub-title
       :%ais-text-label-set-display-type
       :%v3d-viewer-set-default-bg-color
       :%v3d-viewer-set-default-view-proj
       :%v3d-viewer-set-default-view-size
       :%v3d-viewer-set-default-view-type
       :%prsdim-make-length-2p
       :%prsdim-make-angle-3p
       :%prsdim-make-diameter
       :%prsdim-make-radius
       :%prsdim-set-text-position
       :%prsdim-set-display-units
       :%prsdim-set-flyout
       :%prsdim-set-measured-edge
       :%prsdim-set-arrow-length
       :%prsdim-set-extension-size
       :%prsdim-set-custom-value
       :%prsdim-set-angle-edges
       :%ais-context-default-drawer
       :%ais-object-attributes
       :%drawer-shading-aspect
       :%drawer-line-aspect
       :%line-aspect-set-color
       :%line-aspect-set-width
       :%line-aspect-set-type
       :%shading-aspect-set-color
       :%shading-aspect-set-material
       :%ais-object-set-line-color
       :%ais-object-set-line-width
       :%ais-object-set-line-type
       :%ais-object-set-point-color
       :%ais-object-set-point-type
       :%ais-object-set-point-scale
       :%ais-object-set-text-color
       :%ais-object-set-text-font
       :%ais-object-set-text-height
       :%ais-object-set-iso-display
       :%ais-object-set-wire-color
       :%ais-object-set-shading-color
       :%ais-object-set-face-boundary-draw
       :%ais-object-set-free-boundary-draw
       :%v3d-view-set-antialiasing
       :%v3d-view-get-antialiasing
       :%make-cubemap-separate
       :%free-cubemap
       :%v3d-view-set-bg-cubemap
       :%v3d-view-set-bg-image
       :%v3d-view-get-camera-handle
       :%v3d-view-set-camera
       :%v3d-view-set-transparency-method
       :%v3d-view-set-grid-echo
       :%v3d-viewer-set-default-lights
       :%v3d-viewer-set-default-bg-gradient
       :%v3d-viewer-set-rectangular-grid-values
       :%v3d-view-grid-display
       :%v3d-viewer-activate-grid
       :%v3d-viewer-deactivate-grid
       :%v3d-view-invalidate
       :%make-material
       :%ais-set-custom-material
       :%ais-set-transparency
       :%ais-set-material-by-name
       :%ais-material-preset-count
       :%ais-material-preset-name
       :%ais-set-line-width
       :%ais-set-edges-display
       :%ais-set-edge-color
        :%ais-set-selection-mode
        :%ais-deactivate-selection
        :%ais-context-nb-selected
        :%ais-context-init-selected
        :%ais-context-more-selected
        :%ais-context-next-selected
        :%ais-context-selected-interactive
        :%ais-context-selected-shape
        :%ais-context-has-selected-shape
        :%ais-context-set-selected
        :%ais-context-add-or-remove-selected
        :%ais-context-clear-selected
        :%ais-context-is-selected
        :%ais-context-move-to
        :%ais-context-select-detected
        :%ais-context-select-point
        :%ais-context-hilight-selected
        :%ais-context-unhilight-selected
        :%ais-context-fit-selected
        :%ais-context-detected-interactive
        :%ais-context-has-detected
        :%ais-context-clear-detected
        :%ais-context-set-selection-sensitivity
        :%ais-context-set-pixel-tolerance
        :%ais-context-set-automatic-hilight
        :%ais-context-set-to-hilight-selected
        :%ais-set-tessellation
         :%ais-create-trihedron
         :%ais-trihedron-set-datum-mode
         :%ais-trihedron-set-draw-arrows
         :%ais-trihedron-set-size
         :%ais-trihedron-set-transform-pers
          :%ais-trihedron-set-datum-part-color
          :%ais-trihedron-set-text-color
          :%ais-trihedron-set-wireframe-color
        :%make-brep-font-from-file
        :%make-brep-font-from-name
        :%free-brep-font
        :%make-text-shape
        :%make-text-shape-on-plane
        :%make-text-shape-on-plane-full
        :%text-bounding-box
        :%enumerate-fonts
        :%query-font-info
        :%ais-text-label-create
        :%ais-text-label-free
        :%ais-text-label-set-text
        :%ais-text-label-set-position
        :%ais-text-label-set-color
        :%ais-text-label-set-font
        :%ais-text-label-set-height
        :%font-render-glyph
        :%font-ascender
        :%font-descender
        :%font-line-spacing
        :%font-advance-x
        :%font-advance-y
        :%font-set-width-scaling
        :%font-set-composite-curve-mode
        :%font-aspect-value
        :%h-align-value
        :%v-align-value
         :make-shape
      :make-geom2d
      :make-brep-font
      :make-curve
      :make-surface
      :%make-line-3d
      :%make-circle-3d
      :%make-ellipse-3d
      :%make-hyperbola
      :%make-parabola
      :%make-bezier-curve
      :%make-bspline-curve
      :%free-curve
      :%curve-type
      :%make-gc-line
      :%make-gc-arc-of-circle
      :%convert-curve-to-bspline
      :%curve-bounding-box
      :%make-plane
      :%make-cylindrical-surface
      :%make-conical-surface
      :%make-spherical-surface
      :%make-toroidal-surface
      :%make-bezier-surface
      :%make-bspline-surface
      :%free-surface
      :%surface-type
      :%convert-surface-to-bspline
      :%surface-bounding-box
      :%project-point-on-curve
      :%project-point-on-surface
      :%intersect-curves
      :%intersect-curve-surface
      :%intersect-surfaces
      :%extrema-curve-curve
      :%extrema-curve-surface
      :%intersect-curves-2d
      :%project-point-on-curve-2d
      :%points-to-bspline
      :%interpolate-points
       :%make-helix-curve
       :%make-helix-edge
       :%shape-volume
       :%shape-area
       :%shape-center-of-mass
       :%shape-inertia
       :%shape-distance
       :%shape-distance-extrema
       :%classify-point-in-solid
       :%shape-is-valid
       :%shape-analysis-report
       :%intersect-curve-shape
       :%map-subshapes
       :%count-subshapes
       :%dump-shape
       :%shape-triangle-count
       :%wire-order-check
       :%edge-to-curve
       :%face-to-surface
        :%make-vertex
        :%make-polygon
        :%fillet-edge-constant
        :%fillet-edges-constant
        :%fillet-edge-variable
        :%fillet-wire-corner
        :%fillet-wire-all-corners
        :%chamfer-edge-equal
        :%chamfer-edges-equal
        :%chamfer-edge-asym
        :%chamfer-edge-on-face
         :%blend-faces-constant
         :%blend-make-constant
         :%sweep-pipe
         :%sweep-pipe-fixed
         :%sweep-pipe-shell
         :%sweep-pipe-shell-sliding
         :%sweep-pipe-shell-fixed
         :%sweep-pipe-shell-aux
         :%loft-sections
         :%loft-sections-ruled
         :%loft-sections-smooth
         :%loft-sections-tangency
         :%fill-face
         :%fill-face-constrained
         :%fill-n-sided-face
         :%shell-shape
         :%offset-shape-3d
         :%offset-wire-2d
         :%draft-face
         :%make-evolved
         :%make-cylindrical-hole
         :%make-prism-feature
         :%make-revol-feature
         :%make-pipe-feature
          :%local-extrude
          :%make-groove
          :%make-rib
          :%fix-shape
          :%fix-wire
          :%fix-solid
          :%fix-edge
          :%fix-face
          :%shape-analysis-free-edges
          :%shape-analysis-check-intersections
          :%shape-analysis-wire-contains
          :%shape-analysis-contents
          :%substitute-single
          :%substitute-batch
          :%shape-to-nurbs
          :%shape-reduce-degree
          :%shape-to-rational-bspline
          :%shape-split-u
          :%shape-upgrade-continuity
          :%apply-shape-process
          :%apply-operator-sequence
          :%apply-healing-pipeline
          :%heal-shape-default
         :%shape-gprops-internal
       :%shape-distance-extrema-internal
       :%shape-type-to-int
     :%curve-kind->keyword
     :%surface-kind->keyword
))

(defpackage :cl-occt
  (:use :cl :cl-occt.impl)
  (:export
   :shape
   :shape-p
   :geom2d
   :geom2d-p
   :make-pnt2d
   :make-vec2d
   :make-dir2d
   :make-line2d
   :make-circle2d
   :make-edge
   :make-edge-3d
   :make-circle-edge
   :make-circular-arc
   :make-wire
   :make-face
   :make-face-on-plane
   :make-box
   :make-cylinder
   :make-sphere
   :make-cone
   :make-torus
   :make-prism
   :make-revol
   :cut
   :fuse
   :common
   :section
   :translate
   :rotate
   :write-step
   :read-step
   :write-stl
    :read-stl
    :make-compound
    :add-to-compound
    :compound-shape-p
    :read-step-assembly
   :write-step-assembly
    :assembly
   :make-part
   :make-assembly
   :assembly-shape
   :assembly-name
   :assembly-color
   :assembly-location
   :assembly-children
   :assembly-leaf-p
   :assembly-branch-p
   :viewer
    :viewer-p
    :make-viewer
    :free-viewer
    :fit-all
     :must-be-resized
     :with-viewer
     :ais-context
     :ais-context-p
     :ais-object
     :ais-object-p
     :ais-create-context
     :ais-free-context
     :ais-create-shape
     :ais-free
     :ais-display
     :ais-erase
     :ais-remove
     :ais-remove-all
      :ais-displayed-p
      :set-background
      :ais-set-color
      :ais-unset-color
      :ais-set-display-mode
        :set-view-projection
        :viewer-camera
        :viewer-camera-p
        :set-viewer-camera
        :set-camera
        :set-perspective
        :perspective-p
        :set-fov
        :set-clip-planes
        :pan-camera
        :zoom-camera
        :rotate-camera
        :reset-view
       :fit-all
       :set-msaa
      :msaa
      :set-antialiasing
      :antialiasing-p
       :activate-grid
       :deactivate-grid
       :invalidate-view
       :make-trihedron
         :set-trihedron-mode
         :set-trihedron-arrows
         :set-trihedron-size
         :set-trihedron-corner
         :show-trihedron
         :set-trihedron-axis-colors
         :set-trihedron-text-color
         :set-trihedron-wireframe-color
        :ais-set-transparency
        :ais-set-material
        :ais-set-custom-material
        :make-material
        :material-preset-list
        :*material-presets*
        :ais-set-line-width
        :ais-show-edges
        :ais-set-edge-styling
        :ais-set-selection-mode
        :ais-set-selected
        :ais-add-or-remove-selected
        :ais-clear-selected
        :ais-is-selected
        :ais-nb-selected
        :ais-init-selected
        :ais-more-selected
        :ais-next-selected
        :ais-selected-interactive
        :ais-selected-shape
        :ais-has-selected-shape
        :ais-selected-objects
        :ais-selected-shapes
        :ais-move-to
        :ais-select-detected
        :ais-select-point
        :ais-hilight-selected
        :ais-unhilight-selected
        :ais-fit-selected
        :ais-detected-interactive
        :ais-has-detected
        :ais-clear-detected
        :ais-set-selection-sensitivity
        :ais-set-pixel-tolerance
        :ais-set-automatic-hilight
        :ais-set-to-hilight-selected
        :*selection-scheme-map*
        :*status-of-detection-map*
        :*status-of-pick-map*
        :ais-set-tessellation
        :viewer-light
        :viewer-light-p
        :make-light
        :free-light
        :light-type
        :viewer-add-light
        :viewer-remove-light
        :viewer-light-on
        :viewer-light-off
        :viewer-light-active-p
        :viewer-lights
        :viewer-active-lights
        :set-light-color
        :set-light-intensity
        :set-light-direction
        :set-headlight
        :set-light-shadows
        :viewer-default-lights
        :grid-active-p
        :set-rectangular-grid-values
        :set-grid-xy-size
        :set-grid-offset
        :set-grid-color
        :set-grid-size
        :grid-color
        :grid-size
        :grid-offset
        :grid-display
        :set-image-background
        :set-gradient-background
        :set-background-cubemap
        :set-cube-map
        :set-default-bg-gradient
        :*gradient-style-map*
        :reset-background
        :set-computed-mode
        :computed-mode-p
        :set-back-face-model
        :set-frustum-culling
        :set-transparency-method
        :set-transparent-shading
        :redraw-view
        :set-immediate-update
        :set-text-label-angle
        :set-text-label-hjustification
        :set-text-label-vjustification
        :set-text-label-align
        :set-text-label-subtitle-color
        :set-text-label-display-type
        :make-text-label
        :set-default-background
        :set-default-projection
        :set-default-view-size
        :set-default-view-type
        :default-lights
        :set-default-gradient
        :set-default-lights
        :make-dimension
        :set-dimension-text-position
        :set-dimension-units
        :set-dimension-flyout
        :set-dimension-arrow-length
        :set-dimension-extension-size
        :set-dimension-custom-value
        :set-dimension-angle-edges
        :set-dimension-text
        :set-dimension-arrows
        :set-dimension-extension
        :ais-drawer
        :drawer-p
        :drawer-shading-aspect
        :drawer-line-aspect
        :line-aspect-color
        :line-aspect-width
        :line-aspect-type
        :shading-aspect-color
        :ais-set-drawer-line-color
        :ais-set-drawer-line-width
        :ais-set-drawer-line-type
        :ais-set-drawer-point-color
        :ais-set-drawer-point-type
        :ais-set-drawer-point-scale
        :ais-set-drawer-text-color
        :ais-set-drawer-text-font
        :ais-set-drawer-text-height
        :ais-set-drawer-iso-display
        :ais-set-drawer-wire-color
        :ais-set-drawer-shading-color
        :ais-set-drawer-face-boundaries
        :ais-set-drawer-free-boundaries
        :brep-font
        :brep-font-p
        :make-brep-font-from-file
        :make-brep-font-from-name
        :make-text-shape
        :make-text-shape-3d
        :make-text-shape-on-plane
        :text-bounding-box
        :list-available-fonts
        :font-info
        :ais-text-label
        :ais-text-label-p
        :make-ais-text-label
        :ais-free-text-label
        :text-glyph-as-shape
        :text-glyph-as-shape-3d
        :text-font-ascender
        :text-font-descender
        :text-font-line-spacing
        :text-font-advance-x
        :text-font-advance-y
        :text-font-set-width-scaling
        :text-font-set-composite-curve-mode
         :make-multi-line-text
         :make-formatted-text
         :text
         :viewer-color
         :viewer-color-p
         :make-color
         :color-rgb
         :color-r
         :color-g
         :color-b
         :color-name
         :named-color
         :normalize-color
         :hex-to-rgb
         :color-delta
         :list-named-colors
         :named-color-exists-p
         :hls-to-rgb
         :curve
         :curve-p
         :curve-type
         :make-line-3d
         :make-circle-3d
         :make-ellipse
         :make-hyperbola
         :make-parabola
         :make-bezier-curve
         :make-bspline-curve
         :make-gc-line
         :make-gc-arc-of-circle
         :convert-curve-to-bspline
         :curve-bounding-box
         :surface
         :surface-p
         :surface-type
         :make-plane
         :make-cylindrical-surface
         :make-conical-surface
         :make-spherical-surface
         :make-toroidal-surface
         :make-bezier-surface
         :make-bspline-surface
         :convert-surface-to-bspline
         :surface-bounding-box
         :project-point-on-curve
         :project-point-on-surface
         :intersect-curves
         :intersect-curve-surface
         :intersect-surfaces
         :extrema-curve-curve
         :extrema-curve-surface
         :intersect-curves-2d
         :project-point-on-curve-2d
         :points-to-bspline
         :interpolate-points
          :make-helix-curve
          :make-helix-edge
          :gprops
          :gprops-volume
          :gprops-area
          :gprops-center-of-mass
          :gprops-inertia-matrix
          :gprops-principal-moments
          :gprops-principal-axes
          :shape-gprops
          :shape-volume
          :shape-area
          :shape-center-of-mass
          :shape-inertia
          :shape-extrema
          :extrema-distance
          :extrema-point-on-shape1
          :extrema-point-on-shape2
          :shape-distance
          :shape-distance-extrema
          :point-in-solid-p
          :classify-point-in-solid
          :shape-valid-p
          :shape-check
          :intersect-curve-shape
          :map-shape-subshapes
          :count-shape-subshapes
          :dump-shape
          :shape-triangle-count
          :wire-order-check-p
          :edge-&gt;curve
          :face-&gt;surface
           :make-vertex
           :make-polygon
           :fillet-edge
           :fillet-edges
           :fillet-edge-variable
           :fillet-wire-corner
            :fillet-wire-all-corners
            :chamfer-edge
            :chamfer-edges
            :chamfer-edge-asymmetric
            :chamfer-edge-on-face
            :blend-faces
            :make-blend
            :sweep-profile
            :sweep-sections
            :sweep-with-aux-spine
            :loft-sections
             :fill-face
             :fill-n-sided-face
             :shell-shape
             :offset-shape
             :offset-wire
              :draft-face
              :make-evolved
              :make-cylindrical-hole
              :make-prism-feature
              :make-revol-feature
              :make-pipe-feature
               :local-extrude
               :make-groove
               :make-rib
               :fix-shape
               :fix-wire
               :fix-solid
               :fix-edge
               :fix-face
               :shape-analysis-free-edges
               :shape-analysis-check-intersections
               :shape-analysis-wire-contains-p
               :shape-analysis-contents
               :substitute-shape
               :shape-to-nurbs
               :shape-reduce-degree
               :shape-to-rational-bspline
               :shape-split-u
               :shape-upgrade-continuity
               :apply-shape-process
               :apply-healing-pipeline
               :heal-shape))
