(in-package :cl-occt.impl)

(defun dirty-model! (name)
  (let ((m (find-model name)))
    (when m
      (setf (model-dirty m) t)
      (dolist (dep (model-dependents m))
        (dirty-model! dep)))))

(defun topological-sort (model-names)
  (let ((sorted '())
        (visited (make-hash-table :test 'eq))
        (visiting (make-hash-table :test 'eq)))
    (labels ((visit (name)
               (cond ((gethash name visited) nil)
                     ((gethash name visiting)
                      (error "Cycle detected involving ~S" name))
                     (t
                      (setf (gethash name visiting) t)
                      (let ((m (find-model name)))
                        (when m
                          (dolist (dep (model-model-deps m))
                            (visit dep))))
                      (remhash name visiting)
                      (setf (gethash name visited) t)
                      (push name sorted)))))
      (dolist (n model-names)
        (visit n))
      (nreverse sorted))))

(defun param-hash ()
  (sxhash *params*))

(defun evaluate-model (name)
  (let* ((m (find-model name))
         (this-hash (param-hash)))
    (when (and (not (model-dirty m))
               (eql (model-last-param-hash m) this-hash))
      (return-from evaluate-model (model-cached-shape m)))
    (setf (model-dirty m) nil)
    (setf (model-last-param-hash m) this-hash)
    (multiple-value-bind (shape color-val name-val layer-val)
        (funcall (model-fn m))
      (setf (model-cached-shape m) shape)
      (setf (model-color m) color-val)
      (setf (model-display-name m) name-val)
      (setf (model-layer m) layer-val)
      shape)))

(defun propagate-changes ()
  (let* ((all-names (loop for k being the hash-keys of *model-registry* collect k))
         (dirty-names (remove-if-not (lambda (n)
                                       (let ((m (find-model n)))
                                         (and m (model-dirty m))))
                                     all-names))
         (sorted (topological-sort dirty-names)))
    (dolist (name sorted)
      (evaluate-model name))))
